version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
